/* AUTO-GENERATED by tools/icon_gen/gen_telltale_icons.py — do not edit. */
#ifndef LV_IMAGE_TELLTALE_ICONS_H
#define LV_IMAGE_TELLTALE_ICONS_H

#include "lvgl/lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/* 48px variant */
extern const lv_image_dsc_t tt_icon_engine;
extern const lv_image_dsc_t tt_icon_emergency_stop;
extern const lv_image_dsc_t tt_icon_oil_temp;
extern const lv_image_dsc_t tt_icon_coolant_temp;
extern const lv_image_dsc_t tt_icon_oil_press;
extern const lv_image_dsc_t tt_icon_battery;
extern const lv_image_dsc_t tt_icon_fuel;
extern const lv_image_dsc_t tt_icon_water_flow;
extern const lv_image_dsc_t tt_icon_coolant_press;
extern const lv_image_dsc_t tt_icon_lambda;
extern const lv_image_dsc_t tt_icon_rpm_redline;
extern const lv_image_dsc_t tt_icon_can_network;
extern const lv_image_dsc_t tt_icon_shallow_water;
extern const lv_image_dsc_t tt_icon_zoom_in;
extern const lv_image_dsc_t tt_icon_zoom_out;
extern const lv_image_dsc_t tt_icon_tile_missing;
extern const lv_image_dsc_t tt_icon_sd_missing;

/* 32px variant */
extern const lv_image_dsc_t tt_icon_engine_32;
extern const lv_image_dsc_t tt_icon_emergency_stop_32;
extern const lv_image_dsc_t tt_icon_oil_temp_32;
extern const lv_image_dsc_t tt_icon_coolant_temp_32;
extern const lv_image_dsc_t tt_icon_oil_press_32;
extern const lv_image_dsc_t tt_icon_battery_32;
extern const lv_image_dsc_t tt_icon_fuel_32;
extern const lv_image_dsc_t tt_icon_water_flow_32;
extern const lv_image_dsc_t tt_icon_coolant_press_32;
extern const lv_image_dsc_t tt_icon_lambda_32;
extern const lv_image_dsc_t tt_icon_rpm_redline_32;
extern const lv_image_dsc_t tt_icon_can_network_32;
extern const lv_image_dsc_t tt_icon_shallow_water_32;
extern const lv_image_dsc_t tt_icon_zoom_in_32;
extern const lv_image_dsc_t tt_icon_zoom_out_32;
extern const lv_image_dsc_t tt_icon_tile_missing_32;
extern const lv_image_dsc_t tt_icon_sd_missing_32;

/* 24px variant */
extern const lv_image_dsc_t tt_icon_engine_24;
extern const lv_image_dsc_t tt_icon_emergency_stop_24;
extern const lv_image_dsc_t tt_icon_oil_temp_24;
extern const lv_image_dsc_t tt_icon_coolant_temp_24;
extern const lv_image_dsc_t tt_icon_oil_press_24;
extern const lv_image_dsc_t tt_icon_battery_24;
extern const lv_image_dsc_t tt_icon_fuel_24;
extern const lv_image_dsc_t tt_icon_water_flow_24;
extern const lv_image_dsc_t tt_icon_coolant_press_24;
extern const lv_image_dsc_t tt_icon_lambda_24;
extern const lv_image_dsc_t tt_icon_rpm_redline_24;
extern const lv_image_dsc_t tt_icon_can_network_24;
extern const lv_image_dsc_t tt_icon_shallow_water_24;
extern const lv_image_dsc_t tt_icon_zoom_in_24;
extern const lv_image_dsc_t tt_icon_zoom_out_24;
extern const lv_image_dsc_t tt_icon_tile_missing_24;
extern const lv_image_dsc_t tt_icon_sd_missing_24;

#ifdef __cplusplus
}
#endif
#endif
